import array
x=int(input("Enter a value for the array"))
y=int(input("Enter a value for the array"))
z=int(input("Enter a value for the array"))
a=int(input("Enter a value for the array"))
b=int(input("Enter a value for the array"))
arr=array.array('i',[x,y,z,a,b])
print ("The new created array is : ",end=" ")  
print (arr) 
print("\r")